
url = ['https://celebsupdate.com/sonnalli-seygall-net-worth-family-age-height-movies-husband-bio/',
'https://celebsupdate.com/sara-ali-khan-net-worth-wiki-father-mother-brother-age-bio-family/',
'https://celebsupdate.com/kangana-ranaut-age-height-bio-wiki-family-net-worth-boyfriends/',
'https://celebsupdate.com/mouni-roy-net-worth-age-height-weight-family-boyfriends-bio-wiki/',
'https://celebsupdate.com/deepika-padukone-net-worth-age-height-weight-sister-husband-bio/',
'https://celebsupdate.com/shriya-saran-net-worth-age-height-weight-family-husband-wiki-bio/',
'https://celebsupdate.com/mandana-karimi-husband-age-biography-wiki-parents-net-worth/',
'https://celebsupdate.com/daisy-shah-net-worth-age-height-movies-bio-wiki-family-boyfriends/',
'https://celebsupdate.com/esha-gupta-net-worth-age-height-sister-husband-wiki-biography/',
'https://celebsupdate.com/janhvi-kapoor-net-worth-age-sister-family-mother-bio-wiki/',
'https://celebsupdate.com/sunny-leone-age-wiki-family-movies-kids-husband-net-worth-more/',
'https://celebsupdate.com/athiya-shetty-age-height-bio-wiki-family-movies-net-worth-more/',
'https://celebsupdate.com/saba-qamar-age-bio-wiki-weight-education-family-movies-more/',
'https://celebsupdate.com/disha-patani-age-wiki-bio-height-father-movies-net-worth-more/',
'https://celebsupdate.com/amyra-dastur-age-bio-wiki-height-movies-net-worth-affair-more/',
'https://celebsupdate.com/tabu-age-height-wiki-bio-movies-net-worth-full-name-more/',
'https://celebsupdate.com/kareena-kapoor-bio-age-wiki-husband-son-movies-net-worth-more/',
'https://celebsupdate.com/yami-gautam-bio-wiki-age-height-movies-affairs-net-worth-more/',
'https://celebsupdate.com/nushrat-bharucha-age-bio-wiki-height-movies-net-worth-more/',
'https://celebsupdate.com/rakul-preet-singh-bio-age-height-movies-net-worth-songs-more/',
'https://celebsupdate.com/shraddha-kapoor-age-bio-height-wiki-family-affairs-net-worth/',
'https://celebsupdate.com/katrina-kaif-age-height-bio-wiki-affairs-net-worth-family-more/',
'https://celebsupdate.com/kriti-sanon-age-height-bio-family-boyfriends-net-worth-more/',
'https://celebsupdate.com/kiara-advani-age-height-bio-wiki-boyfriends-net-worth-more/',
'https://celebsupdate.com/alia-bhatt-age-height-weight-bio-wiki-family-movies-net-worth-boyfriends/']