
url = ['https://celebsupdate.com/rajkummar-rao-net-worth-age-height-weight-family-bio-wiki/',
'https://celebsupdate.com/ronit-roy-net-worth-age-height-bio-wiki-family-wife-children/',
'https://celebsupdate.com/sooraj-pancholi-age-height-weight-family-sister-bio-wiki/',
'https://celebsupdate.com/himesh-reshammiya-net-worth-age-height-weight-family-wife-son/',
'https://celebsupdate.com/kartik-aaryan-age-height-weight-bio-wiki-parents-sister-net-worth/',
'https://celebsupdate.com/karan-singh-grover-biography-wiki-age-wife-kids-net-worth-spouse/',
'https://celebsupdate.com/pulkit-samrat-net-worth-age-height-family-father-wife-gf-bio-movies/',
'https://celebsupdate.com/pankaj-tripathi-net-worth-age-height-weight-wife-daughter-bio-wiki/',
'https://celebsupdate.com/akshay-kumar-net-worth-age-height-weight-wife-children-son-wiki/',
'https://celebsupdate.com/vicky-kaushal-net-worth-age-height-weight-family-awards-bio-wiki/',
'https://celebsupdate.com/vikrant-massey-net-worth-age-height-weight-family-fiancee-wife/',
'https://celebsupdate.com/sunny-singh-net-worth-age-height-weight-family-bio-wiki/',
'https://celebsupdate.com/nawazuddin-siddiqui-bio-wiki-age-height-wife-movies-kids-more/',
'https://celebsupdate.com/sidharth-malhotra-age-bio-wiki-height-upcoming-movies-net-worth/',
'https://celebsupdate.com/riteish-deshmukh-wiki-age-bio-wife-son-movies-net-worth-more/',
'https://celebsupdate.com/hrithik-roshan-biography-wiki-age-family-movies-wife-kids-more/',
'https://celebsupdate.com/tiger-shroff-biography-height-age-movies-net-worth-affairs-more/',
'https://celebsupdate.com/salman-khan-age-bio-wiki-height-education-family-affairs-more/',
'https://celebsupdate.com/varun-dhawan-age-bio-wiki-family-father-wife-brother-movies/',
'https://celebsupdate.com/shah-rukh-khan-age-bio-wiki-wife-son-daughter-movies/',
'https://celebsupdate.com/aamir-khan-age-wife-son-daughter-bio-career-movies/',
'https://celebsupdate.com/vidyut-jamwal-age-bio-new-movies-height-mother-net-worth-more/',
'https://celebsupdate.com/diljit-dosanjh-bio-wiki-age-movies-wife-songs-net-worth-more/',
'https://celebsupdate.com/ali-fazal-net-worth-wife-age-height-weight-family-movies/']